const store = [
    {
        name: "Jordan 1 Retro High",
        color: "White University Blue Black",
        inStock: false,
        img: "https://images.stockx.com/images/Air-Jordan-1-Retro-High-White-University-Blue-Black-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1611777406",
        price: "399",
        category: "shoe",
    },
    {
        name: "Jordan 1 Retro High",
        color: "DIOR",
        inStock: false,
        img: "https://images.stockx.com/images/Air-Jordan-1-Retro-High-Dior-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1607043976",
        price: "8,700",
        category: "shoe",
    },
    {
        name: "Louis Vuitton Monogram Chain Necklace",
        color: "Silver",
        inStock: true,
        img: "https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-monogram-chain-necklace-fashion-jewelry--M00307_PM1_Side%20view.png?wid=824&hei=824",
        price: "925",
        category: "jewelry",
    },
    {
        name: "Jordan 1 Mid",
        color: "Light Bone",
        inStock: true,
        img: "https://image.goat.com/transform/v1/attachments/product_template_additional_pictures/images/060/556/620/original/816402_01.jpg.jpeg?action=crop&width=950",
        price: "210",
        category: "shoe",
    },
    {
        name: "Jordan 1 Low",
        color: "Pine Green",
        inStock: true,
        img: "https://images.stockx.com/images/Air-Jordan-1-Low-Pine-Green-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1608515932",
        price: "340",
        category: "shoe",
    },
    {
        name: "Jordan 1 Mid SE",
        color: "All Star 2021",
        inStock: true,
        img: "https://image.goat.com/transform/v1/attachments/product_template_additional_pictures/images/047/771/312/original/715117_01.jpg.jpeg?action=crop&width=2000",
        price: "215",
        category: "shoe",
    },
    {
        name: "Jordan 1 Mid",
        color: "Purple Aqua",
        inStock: true,
        img: "https://images.stockx.com/images/Air-Jordan-1-Mid-Purple-Aqua-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1619201529 ",
        price: "200",
        category: "shoe",
    },
    {
        name: "Jordan 1 Retro High",
        color: "Turbo Green",
        inStock: true,
        img: "https://images.stockx.com/images/Air-Jordan-1-Retro-High-Turbo-Green-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1606324093",
        price: "600",
        category: "shoe",
    },
    {
        name: "Jordan 4 Retro",
        color: "Fire Red",
        inStock: true,
        img: " https://images.stockx.com/images/Air-Jordan-4-Retro-Fire-Red-2020-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1606762588",
        price: "350",
        category: "shoe",
    },
    {
        name: "Jordan 1 Retro High",
        color: "Court Purple White",
        inStock: true,
        img: "https://images.stockx.com/images/Air-Jordan-1-Retro-High-Court-Purple-White-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1606321166",
        price: "400",
        category: "shoe",
    },
    {
        name: "Jordan 4 Retro",
        color: "Winterized Loyal Blue",
        inStock: true,
        img: " https://images.stockx.com/images/Air-Jordan-4-Retro-Winter-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1606316899",
        price: "339",
        category: "shoe",
    },
    {
        name: "Jordan 4 Retro",
        color: "White Loyal Purple",
        inStock: false,
        img: " https://images.stockx.com/images/Air-Jordan-4-Retro-White-Court-Purple-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1606315846",
        price: "350",
        category: "shoe",
    },
    {
        name: "Kay Cuban Chain Necklace",
        color: "10K Yellow",
        inStock: true,
        img: "https://www.kay.com/productimages/processed/V-714926007_0_565.jpg?pristine=true",
        price: "1,199",
        category: "jewelry",
    },
    {
        name: "Jordan 1 Mid",
        color: "Chicago Toe",
        inStock: true,
        img: " https://cdn.flightclub.com/TEMPLATE/165290/1.jpg",
        price: "333",
        category: "shoe",
    },
    {
        name: "Return to Tiffany",
        color: "Ultra Oval Tag Bracelet",
        inStock: false,
        img: "https://media.tiffany.com/is/image/Tiffany/EcomItemL2/return-to-tiffanyultra-oval-tag-bracelet-68892570_1016762_ED_M.jpg?&op_usm=1.0,1.0,6.0&$cropN=0.1,0.1,0.8,0.8&defaultImage=NoImageAvailableInternal&&wid=1250&hei=1250",
        price: "525",
        category: "jewelry",
    },
    {
        name: "Olive Leaf Bypass Ring",
        color: "Silver",
        inStock: true,
        img: "https://media.tiffany.com/is/image/Tiffany/EcomItemL2/paloma-picassoolive-leaf-bypass-ring-67544315_999198_ED_M.jpg?&op_usm=1.75,1.0,6.0&$cropN=0.1,0.1,0.8,0.8&defaultImage=NoImageAvailableInternal&",
        price: "325",
        category: "jewelry",
    },
    {
        name: "Jordan 4 Retro",
        color: "Lightning",
        inStock: true,
        img: "https://image.goat.com/transform/v1/attachments/product_template_additional_pictures/images/058/005/415/original/704168_01.jpg.jpeg?action=crop&width=950",
        price: "269",
        category: "shoe",
    },
    {
        name: "Olive Leaf Bypass Ring",
        color: "Gold",
        inStock: true,
        img: "https://media.tiffany.com/is/image/Tiffany/EcomItemL2/paloma-picassoolive-leaf-bypass-ring-67544420_999203_ED_M.jpg?&op_usm=1.75,1.0,6.0&$cropN=0.1,0.1,0.8,0.8&defaultImage=NoImageAvailableInternal&",
        price: "325",
        category: "jewelry",
    },
    {
        name: "Jordan 1 Mid",
        color: "Tan Gum",
        inStock: true,
        img: "https://image.goat.com/transform/v1/attachments/product_template_additional_pictures/images/060/102/466/original/793318_01.jpg.jpeg?action=crop&width=950",
        price: "169",
        category: "shoe",
    },
    {
        name: "Textured Rhinestone Sterling Ring",
        color: "Silver",
        inStock: true,
        img: "https://d1flfk77wl2xk4.cloudfront.net/Assets/57/140/XXL_p0149314057.jpg",
        price: "40",
        category: "jewelry",
    },
    {
        name: "Travis Scott x Jordan 1 Retro High OG",
        color: "Mocha",
        inStock: false,
        img: "https://image.goat.com/transform/v1/attachments/product_template_additional_pictures/images/018/783/118/original/488879_01.jpg.jpeg?action=crop&width=950",
        price: "2,021",
        category: "shoe",
    },
    {
        name: "Travis Scott x Jordan 6 Retro",
        color: "British Khaki",
        inStock: false,
        img: "https://image.goat.com/transform/v1/attachments/product_template_additional_pictures/images/053/983/839/original/687698_01.jpg.jpeg?action=crop&width=950",
        price: "457",
        category: "shoe",
    },
    {
        name: "Fragment Design x Travis Scott x Air Jordan 1 Retro Low",
        color: " ",
        inStock: false,
        img: "https://image.goat.com/transform/v1/attachments/product_template_additional_pictures/images/059/084/576/original/767449_01.jpg.jpeg?action=crop&width=950",
        price: "1,721",
        category: "shoe",
    },
    {
        name: "Bear Pendant Necklace",
        color: "Silver",
        inStock: true,
        img: "https://d1flfk77wl2xk4.cloudfront.net/Assets/28/312/XXL_p0163231228.jpg",
        price: "50",
        category: "jewelry",
    },
    {
        name: "Sugar Lump - Star Pendant Necklace",
        color: "Star white",
        inStock: true,
        img: "https://d1flfk77wl2xk4.cloudfront.net/Assets/56/048/XXL_p0156904856.jpg",
        price: "45.47",
        category: "jewelry",
    },
    {
        name: "Trophy Room x Air Jordan 1 Retro High OG SP",
        color: "Chicago Friends & Family",
        inStock: true,
        img: "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/050/477/184/original/DA2728_100_FF.png.png?action=crop&width=950",
        price: "2,900",
        category: "shoe",
    },
    {
        name: "SWART Sterling Open Bangle",
        color: "Silver",
        inStock: true,
        img: "https://d1flfk77wl2xk4.cloudfront.net/Assets/53/553/XXL_p0157155353.jpg",
        price: "300",
        category: "jewelry",
    },
    {
        name: "Star Pendant Sterling Silver Choker",
        color: "Silver",
        inStock: true,
        img: "https://d1flfk77wl2xk4.cloudfront.net/Assets/65/074/XXL_p0155007465.jpg",
        price: "55.66",
        category: "jewelry",
    },
    {
        name: "Jordan 1 Retro High",
        color: "Off-White University Blue",
        inStock: true,
        img: "https://images.stockx.com/images/Air-Jordan-1-Retro-High-Off-White-University-Blue-Product.jpg",
        price: "2,000",
        category: "shoe",
    },
    {
        name: "Bear Pendant Layered Necklace",
        color: "Silver",
        inStock: true,
        img: "https://d1flfk77wl2xk4.cloudfront.net/Assets/22/237/XXL_p0122723722.jpg",
        price: "65",
        category: "jewelry",
    },
    {
        name: "Gucci Ghost Silver Ring",
        color: "Silver",
        inStock: false,
        img: "https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1470213005/455318_J8400_0701_002_100_0000_Light-GucciGhost-skull-ring-in-silver.jpg",
        price: "270",
        category: "jewelry",
    },
    {
        name: "PANGU Chain Necklace",
        color: "Silver",
        inStock: true,
        img: "https://d1flfk77wl2xk4.cloudfront.net/Assets/91/021/L_p0126502191.jpg",
        price: "90",
        category: "jewelry",
    },
    {
        name: "Jordan 3 Retro",
        color: "A Ma Maniére White ",
        inStock: true,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8PFdKsIJX-QGx4oPXLIIxm_o7PO2iSCc0l-SqlrS-MlSmiZwALt7QUYYqI5NPJhlFQLg&usqp=CAU",
        price: "650",
        category: "shoe",
    },
    {
        name: "Air Jordan 1 Retro High",
        color: "Turbo Green/Sail-White-Light Smoke Grey",
        inStock: false,
        img: "https://images.solecollector.com/complex/image/upload/c_fill,f_auto,fl_lossy,q_auto,w_1100/pvuzhwvveeqvxlaq1mv5.jpg",
        price: "1,690",
        category: "shoe",
    },
    {
        name: "Jordan 1 Low",
        color: "White Pollen (GS)",
        inStock: true,
        img: "https://images.stockx.com/images/Air-Jordan-1-Low-Mustard-GS.jpg?fit=fill&bg=FFFFFF&w=480&h=320&auto=compress&q=90&dpr=2&trim=color&updated_at=1623474194&pad=0&fm=webp",
        price: "120",
        category: "shoe",
    },
    {
        name: "Jordan 6 Retro",
        color: "Carmine",
        inStock: true,
        img: "https://images.stockx.com/images/Air-Jordan-6-Retro-Carmine-2020-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1612286105",
        price: "500",
        category: "shoe",
    },


];
export { store };